name: Steam Build

on:
  push:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  pull_request:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']

env:
  STEAM_APPID: 847560

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            git
            ruby
            vim
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-gcc

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout steam-sdk
        uses: actions/checkout@v5
        with:
          repository: stesproject/steam-sdk
          path: steam_sdk
          token: ${{ secrets.SDK_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: |
            windows/build-mingw64
            windows/downloads
          key: win-${{ hashFiles('windows/Makefile') }}

      - name: Clear Windows Cache
        shell: msys2 {0}
        run: rm -rf windows/build-mingw64 windows/downloads
        
      - name: Build all dependencies
        shell: msys2 {0}
        run: |
          cd windows
          make

      - name: Build exe
        shell: msys2 {0}
        run: |
          source windows/vars.sh
          meson setup build -Dsteamworks_path=../steam_sdk -Dsteam_appid=$STEAM_APPID -Denable-https=false
          cd build
          ninja
          strip ./mkxp-z.exe

      - name: Prepare archive
        shell: msys2 {0}
        run: |
          mkdir build/artifact
          cd build/artifact
          cp /mingw64/bin/zlib1.dll .
          cp ../../windows/build-mingw64/bin/x64-msvcrt-ruby310.dll .
          cp -r ../../windows/build-mingw64/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../mkxp-z.exe .
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../assets/LICENSE.mkxp-z-with-https.txt .
          cp ../../steam_sdk/redistributable_bin/win64/steam_api64.dll .
          echo $STEAM_APPID > steam_appid.txt

      - name: Check for DLLs missing from the artifact
        shell: msys2 {0}
        run: |
          cd build/artifact
          error_flag=

          for file in *.exe *.dll
          do
            ldd_output="$(ldd "$file")"
            echo "$file"
            echo "$ldd_output"

            while IFS= read -r line
            do
              dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
              if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
              then
                error_flag=1
                echo "::error::$dll_name is missing from the artifact"
              fi
            done <<< "$ldd_output"
          done

          if [ -n "$error_flag" ]
          then
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/artifact

  build-linux-native:
    name: Ubuntu 22.04 x86_64
    runs-on: ubuntu-22.04
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout steam-sdk
        uses: actions/checkout@v5
        with:
          repository: stesproject/steam-sdk
          path: steam_sdk
          token: ${{ secrets.SDK_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: |
            linux/build-x86_64
            linux/downloads
          key: lin-x86_64-${{ hashFiles('linux/Makefile') }}

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install git wget build-essential cmake meson autoconf automake libtool pkg-config ruby bison xxd zlib1g-dev libbz2-dev xorg-dev libgl1-mesa-dev libasound2-dev libpulse-dev -y

      - name: Clear Linux Cache
        run: rm -rf linux/build-x86_64 linux/downloads

      - name: Build everything else
        run: |
          cd linux
          make

      - name: Build executable
        run: |
          source linux/vars.sh
          meson setup build --bindir=. --prefix=$GITHUB_WORKSPACE/build/local -Dsteamworks_path=steam_sdk -Dsteam_appid=$STEAM_APPID -Denable-https=false
          cd build
          ninja
          ninja install || true

      - name: Prepare archive
        run: |
          cd build/local
          cp -r ../../linux/build-x86_64/lib/ruby/3.1.0 .
          mv ./3.1.0 ./stdlib
          cp ../../mkxp.json .
          cp -r ../../scripts .
          cp ../../steam_sdk/redistributable_bin/linux64/libsteam_api.so .
          echo $STEAM_APPID > steam_appid.txt

      - uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.linux.ubuntu
          path: build/local